In [5]:
# We first import numpy
import numpy as np

In [10]:
# We create a base list, to give something to np to start working with
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [11]:
# Create a Numpy Array(a one dimensional list like object)
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [15]:
# This crates a matrix(a two dimensional list like object)
my_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
my_matrix = np.array(my_list2)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.linspace(0, 10, 51) # Linear space

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.random.rand(3, 3)

array([[0.74857622, 0.14866716, 0.10017864],
       [0.32852414, 0.92870025, 0.681662  ],
       [0.40978269, 0.21284586, 0.09475143]])

In [39]:
np.random.randn(5, 5)

array([[ 0.39284718,  0.716739  ,  0.4721482 ,  0.57194005,  0.51316081],
       [ 0.44591613,  1.64377241, -0.86970101, -0.55703502,  0.07511842],
       [ 0.57341221,  0.62478222, -0.70077576, -0.0924203 ,  0.09924707],
       [-0.74999236, -0.12929733,  0.40536465, -0.58652275, -0.83145666],
       [-0.59909108,  0.87977613,  0.56155466,  2.35729913, -0.81746225]])

In [43]:
np.random.randint(1, 100)

29

In [44]:
np.random.randint(1, 100, 10)

array([95, 95, 23, 84, 93, 76, 32, 33,  2, 44])

In [71]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[29 10 22 32  8 46 15 11 16  9]


In [53]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
arr.shape

(25,)

In [56]:
arr.reshape(5, 5).shape

(5, 5)

In [62]:
arr.dtype

dtype('int32')

In [65]:
ranarr.max()

25

In [69]:
ranarr.argmax()

0

In [67]:
ranarr.min()

5

In [68]:
ranarr.argmin()

6

In [ ]:
|