In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5] = 100 # This is called broadcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr # The slice if a view of the original array, so changing the slice changes the original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy() # To not change the original array, we create a copy of it
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy[:] = 200
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
# To index into a matrix we can use one of the following ways
# mat[row, col]
# mat[row][col]
mat = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
mat[0]

array([ 5, 10, 15])

In [20]:
mat[1][1]

25

In [21]:
mat[1, 1]

25

In [25]:
mat[:2, 1:] # Slicing

array([[10, 15],
       [25, 30]])

In [26]:
# Conditional Selection
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])